main: aut.izanamineko.lobbysystem2021.main
name: LobbySystem
version: V4.2C-MC.18
api-version: 1.18
softdepend:
  - PlaceholderAPI
commands:
  chatclear:
    description: Use /chatclear to Clear the Chat
  cc:
    description: Use /cc to Clear the Chat
  setspawn:
    description: Use /setlobby to set the lobby.
  spawn:
    description: Use /lobby to teleport to the Spawn.s
  setwarp:
    description: Use /setwarp "name" to set a warppoint
  warp:
    description: Use /warp "name" to teleport to the warppoint
  delwarp:
    description: Use /delwarp "name" to delete the Warppoint
  warplist:
    description: Use /warplist to get every Warppoint set right now!
  lobbysystem:
    aliases:
      - ls
    description: Use /lobbysystem for Informations
  ping:
    description: Use /ping to see your Latency
  bug:
    description: Use /bug to report a bug
  kit:
    description: testing