name: LobbySystem2021
main: aut.izanamineko.lobbysystem2021.main
version: 2021.0.ALPHA
api-version: 1.16
commands:
  chatclear:
    description: Use /chatclear to Clear the Chat
  cc:
    description: Use /cc to Clear the Chat
  setlobby:
    description: Use /setlobby to set the lobby.
  lobby:
    description: Use /lobby to teleport to the Spawn.